Fixes after selection preview rework
MSEP-one/msep.one pull request #58
Opened 2024-11-08 08:20 UTC by kubecz3k

Selected shape preview behaves as it appears inconsistently

-----------
    fix selection-preview for flat theme 🔨
    
    Flat theme has never been updated to work in new selection preview
    This commit fixes this oversight by applying changes needed for it to
    work

    refresh selection preview for shapes and motors 🔧
    
    This commit ensures the selection previews for shapes and motors will
    update on every motor/shape transform change

2024-11-08 08:59 UTC, kubecz3k commented
I have seen this pr is needed in order to unblock a task, please feel free to merge it as soon as it's approved. 
I will address any eventual feedback in subsequent pr

2024-11-08 12:44 UTC, MarianoGnu commented
> I have seen this pr is needed in order to unblock a task, please feel free to merge it as soon as it's approved. I will address any eventual feedback in subsequent pr

That task is blocked only because the regression of this PR was wrongly attributed to the PR of that task, there's no rush because this will fix it

2024-11-08 12:54 UTC, MarianoGnu requested changes
Code looks good, but please rebase the code to make use of the already existing `virtual_object_transform_changed` signal, which as a plus will also consider `NanoVirtualAnchor`, not covered in this PR

2024-11-08 12:54 UTC, MarianoGnu commented on godot_project/project_workspace/workspace_context/workspace_context.gd
> +signal motor_transformed(transform: Transform3D, structure_context_id: int)
FYI: #54 intriduced [`signal virtual_object_transform_changed(structure_context: StructureContext)`](https://github.com/MSEP-one/msep.one/blob/a85d4ba3cdc11a4775a989cad43ef29ffb837444/godot_project/project_workspace/workspace_context/workspace_context.gd#L11)

2024-11-10 22:15 UTC, MarianoGnu approved these changes

2024-11-11 07:22 UTC, merged